    features = [
        'return_5',  # 5日收益
        'return_10',  # 10日收益
        'return_20',  # 20日收益
        'return_40',  # 40日收益
        'rank_return_5',  # 5日收益排名
        'rank_return_10',  # 10日收益排名
        'rank_return_20',  # 20日收益排名
        'rank_return_40',  # 40日收益排名
        'avg_turn_5',  # 5日平均换手率
        'avg_turn_10',  # 10日平均换手率
        'avg_turn_20',  # 20日平均换手率
        'avg_turn_40',  # 40日平均换手率
        'avg_amount_5',  # 5日平均交易额
        'avg_amount_10',  # 10日平均交易额
        'avg_amount_20',  # 20日平均交易额
        'avg_amount_40',  # 40日平均交易额
        '(volume_0+volume_1+volume_2+volume_3+volume_4)/5',  # 5日平均交易量
        '(volume_0+volume_1+volume_2+volume_3+volume_4+volume_5+volume_6+volume_7+volume_8+volume_9)/10',  # 10日平均交易量
        '(volume_0+volume_1+volume_2+volume_3+volume_4+volume_5+volume_6+volume_7+volume_8+volume_9+volume_10+volume_11+volume_12+volume_13+volume_14+volume_15+volume_16+volume_17+volume_18+volume_19)/20',  # 20日平均交易量
        '(high_0-low_0+high_1-low_1+high_2-low_2+high_3-low_3+high_4-low_4)/5',  # 5日平均振幅
        'fs_common_equity_0',  # 普通股总权益
        'market_cap_0',  # 总市值
        'rank_market_cap_0',  # 总市值排名
        'market_cap_float_0',  # 流通市值
        'rank_market_cap_float_0',  # 流通市值排名
        'pe_ttm_0',  # 市盈率TTM
        'rank_pe_ttm_0',  # 市盈率TTM排名
        'pe_lyr_0',  # 市盈率LYR
        'rank_pe_lyr_0',  # 市盈率LYR排名
        'pb_lf_0',  # 市净率
        'rank_pb_lf_0',  # 市净率排名
        'ps_ttm_0',  # 市销率
        'rank_ps_ttm_0',  # 市销率排名
        'mf_net_amount_5',  # 5日净主动买入额
        'mf_net_amount_10',  # 10日净主动买入额
        'mf_net_amount_20',  # 20日净主动买入额
        'avg_mf_net_amount_5',  # 5日平均净主动买入额
        'avg_mf_net_amount_10',  # 10日平均净主动买入额
        'avg_mf_net_amount_20',  # 20日平均净主动买入额
        'rank_avg_mf_net_amount_5',  # 5日平均净主动买入额排名
        'rank_avg_mf_net_amount_10',  # 10日平均净主动买入额排名
        'rank_avg_mf_net_amount_20',  # 20日平均净主动买入额排名
        'fs_net_profit_0',  # 归属母公司股东净利润
        'fs_net_profit_ttm_0',  # 归属母公司股东净利润TTM
        'fs_deducted_profit_0',  # 扣除经常性损益后净利润
        'fs_deducted_profit_ttm_0',  # 扣除经常性损益后净利润TTM
        'fs_gross_profit_margin_0',  # 销售毛利率
        'fs_gross_profit_margin_ttm_0',  # 销售毛利率TTM
        'fs_net_profit_margin_0',  # 销售净利率
        'fs_net_profit_margin_ttm_0',  # 销售净利率TTM
        'fs_operating_revenue_0',  # 营业收入
        'fs_operating_revenue_ttm_0',  # 营业收入TTM
        'fs_net_profit_yoy_0',  # 归属母公司股东净利润同比增长率
        'rank_fs_net_profit_yoy_0',  # 归属母公司股东净利润同比增长率排名
        'fs_net_profit_qoq_0',  # 归属母公司股东净利润单季度环比增长率
        'rank_fs_net_profit_qoq_0',  # 归属母公司股东净利润单季度环比增长率排名
        'fs_operating_revenue_yoy_0',  # 营业收入同比增长率
        'rank_fs_operating_revenue_yoy_0',  # 营业收入同比增长率排名
        'fs_operating_revenue_qoq_0',  # 营业收入单季度环比增长率
        'rank_fs_operating_revenue_qoq_0',  # 营业收入单季度环比增长率排名
        'fs_eps_yoy_0',  # 每股收益同比增长率
        'fs_roe_0',  # 净资产收益率
        'fs_roe_ttm_0',  # 净资产收益率TTM
        'fs_roa_0',  # 总资产报酬率
        'fs_roa_ttm_0',  # 总资产报酬率TTM
        'fs_eps_0',  # 每股收益
        'fs_bps_0',  # 每股净资产
        'fs_cash_ratio_0',  # 现金比率
        'fs_operating_revenue_ttm_0/(fs_current_assets_0+fs_non_current_assets_0)',  # 总资产周转率
        'fs_current_assets_0/fs_current_liabilities_0',  # 流动比率
        '(fs_current_liabilities_0+fs_non_current_liabilities_0)/(fs_current_assets_0+fs_non_current_assets_0)',  # 资产负债率
        '(fs_current_liabilities_0+fs_non_current_liabilities_0)/ fs_common_equity_0',  # 产权比率
        'fs_free_cash_flow_0',  # 企业自由现金流
        'fs_net_cash_flow_0',  # 经营活动产生的现金流量净额
        'fs_net_cash_flow_ttm_0',  # 经营活动现金净流量TTM
        'fs_current_assets_0',  # 流动资产
        'fs_non_current_assets_0',  # 非流动资产
        'fs_current_liabilities_0',  # 流动负债
        'fs_non_current_liabilities_0',  # 非流动负债
        'sh_holder_avg_pct_3m_chng_0',  # 户均持股比例
        'rank_sh_holder_avg_pct_0',  # 户均持股比例排名
        'sh_holder_avg_pct_3m_chng_0',  # 户均持股比例季度增长率
        'rank_sh_holder_avg_pct_3m_chng_0',  # 户均持股比例季度增长率排名
        'sh_holder_avg_pct_6m_chng_0',  # 户均持股比例半年增长率
        'rank_sh_holder_avg_pct_6m_chng_0',  # 户均持股比例半年增长率排名
        'ta_sma_5_0',  # 5日移动平均
        'ta_sma_10_0',  # 10日移动平均
        'ta_sma_20_0',  # 20日移动平均
        'ta_atr_14_0',  # 14日平均真实波幅
        'ta_atr_28_0',  # 28日平均真实波幅
        'ta_mfi_14_0',  # 14日资金流量指标
        'ta_mfi_14_0',  # 28日资金流量指标
        'ta_rsi_14_0',  # 14日相对强弱指标
        'ta_rsi_28_0',  # 28日相对强弱指标
        'ta_mom_10',  # 10日动量
        'ta_mom_20',  # 20日动量
        'ta_mom_30',  # 30日动量
        'ta_mom_60',  # 60日动量
        'ta_willr_14_0',  # 14日威廉指标
        'ta_willr_28_0',  # 28日威廉指标
        'list_days_0',  # 已经上市的天数
        'list_board_0',  # 上市板
        'company_found_date_0',  # 公司成立天数
        'st_status_0',  # ST状态
    ]